const fieldNames = {
    remarks: 'Remarks',
    nature: 'Nature',
    typ: 'Type',
    sales: 'Sales',
    trans: 'Transfer Location',
    prop: 'Property Donation',
    repr: 'For Repair',
    repl: 'For Replacement',
    borr: 'Borrowed Items / Equipment',
    etc: 'Others',
    spec: 'Specifications',
    receipt_num: 'Receipt Number',
    reqs: 'Attachments Required',
    xor: 'XU Official Required',
    atfmr: 'Accomplished Transfer Form with MR',
    ass: 'Assessment from CISO or PPO',
    req2borr: 'Request to Borrow Form',
    ptcs: 'Particulars',
    item: 'Item',
    type: 'Type',
    tag: 'Tag',
    num: 'Number of Items',
    amt: 'Amount',
    req: 'Requestor',
    sign: 'Signature',
    ver: 'Verifier',
    title: 'Title',
    appr: 'Approver',
    rcv: 'Receiver',
    done: 'Status',
    orn: 'Official Receipt Number',
    from: 'From',
    to: 'To',
    tfno: 'Transfer Form Number',
    warranty: 'Warranty',
    company: 'Company',
    location: 'Location',
    return: 'Return'
}

export default fieldNames;